### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by asabil** [johanneswuerbach/terraform-provider-sshtunnel#1]
Hi,

I just gave a try to this provider and encountered a segfault on the first try:

```
Stack trace from the terraform-provider-sshtunnel_v0.1.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x623b80]

goroutine 52 [running]:
github.com/johanneswuerbach/terraform-provider-sshtunnel/internal/provider.handleConnection({0x8f5d58, 0x4000358270}, 0x0?, {0x8faab8, 0x40003b0010}, {0x40001d6bf0?, 0x0?})
        github.com/johanneswuerbach/terraform-provider-sshtunnel/internal/provider/connection_ephemeral_resource.go:290 +0x150
created by github.com/johanneswuerbach/terraform-provider-sshtunnel/internal/provider.(*ConnectionEphemeralResource).createPortForward.func1 in goroutine 65
        github.com/johanneswuerbach/terraform-provider-sshtunnel/internal/provider/connection_ephemeral_resource.go:262 +0x80

Error: The terraform-provider-sshtunnel_v0.1.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by asabil** [comment]
This seems to occur if I use `localhost` instead of `127.0.0.1` as the remote host:

```
  local_port_forwardings = [{
    local_port  = 12345
    remote_host = "localhost"
    remote_port = 12345
  }]
```

**Comment by johanneswuerbach** [comment]
Thanks, I found the issue https://github.com/johanneswuerbach/terraform-provider-sshtunnel/pull/2. Are there any logs indicating beforehand why the connection failed?

**Comment by asabil** [comment]
That was a race condition I believe, where the connection would fail because the target was still being created.

On that note, would it be possible to add a "retry" or "delay" mechanism to this provider?

**Comment by johanneswuerbach** [comment]
Yes, both seems reasonable 👍 Would you mind opening another issue for that?

**Comment by asabil** [comment]
Done, thank you!
